services:
  app:
    image: ${IMAGE}
    pull_policy: "missing"
    init: true
    volumes:
      - type: bind
        source: "./"
        target: "/root/work"
        consistency: "consistent"
    entrypoint: /root/show-help-in-app-container-then-wait.sh
    working_dir: /root/work
    ports:
      - "6502:6502"
  postgres:
    image: postgres:16
    pull_policy: "missing"
    environment:
      POSTGRES_PASSWORD: postgres
