services:
  app:
    image: ${IMAGE}
    pull_policy: "missing"
    init: true
    volumes:
      - type: bind
        source: "./"
        target: "/root/work"
        consistency: "consistent"
      - type: bind
        source: "../brut"
        target: "/root/local-gems/brut"
        consistency: "consistent"
      # This allows docker build commands run inside Docker to work
      - type: bind
        source: "/var/run/docker.sock"
        target: "/var/run/docker.sock"
    entrypoint: /root/show-help-in-app-container-then-wait.sh
    working_dir: /root/work
    ports:
      - "6502:6502"
      - "6503:6503"
  postgres:
    image: postgres:16
    pull_policy: "missing"
    environment:
      POSTGRES_PASSWORD: postgres
  redis:
    image: valkey/valkey:7.2
