services:
  app:
    image: davetron5000/adr:1.0
    init: true
    environment:
      SESSION_SECRET: "1de0b3317d9b2b22189223bba5a67132d86014673edc78afea5f3b772323da3f6157521b394c32bf96e4f8a679ca0eb7dcef724f2ebf7a82c0d8ad76"
      DATABASE_URL: "postgres://postgres:postgres@postgres:5432/adrpg_production"
    ports:
      - "6502:6502"
  postgres:
    image: postgres:16
    pull_policy: "missing"
    environment:
      POSTGRES_PASSWORD: postgres
